kind: pipeline
name: default


steps:
    - name: Build website
      image: node
      commands:
          - npm install
          - npm run build
    - name: Build docker image & push to local docker registery
      when:
        branch:
          - master
        event:
          - push
      image: plugins/docker
      settings:
          registry: registery.remicaillot.fr
          auto_tag: true
          repo: registery.remicaillot.fr/respire
          dockerfile: ./Dockerfile
    - name: Deploy to server
      when:
        branch:
          - master
        event:
          - push
      image: docker:dind
      volumes:
        - name: dockersock
          path: /var/run/docker.sock
      commands:
        - docker pull registery.remicaillot.fr/respire:latest
        - docker stop respire
        - docker rm -f respire
        - docker run --name respire -p 9005:80 --hostname respire.remicaillot.fr -d registery.remicaillot.fr/respire
    - name: Discord notification
      image: appleboy/drone-discord
      webhook_id: "587664375846797314"
      webhook_token: "Zc04aQE4dGBxOQcN62fma7X7uwKwV5kacpct_jGo3Uifx7lQCmwARb37HsPv-hgGFeB6"
      message: |
          {{ #success build.status }}
            build {{ build.number }} from {{ build.branch }} succeeded.
          {{ else }}
            build {{ build.number }} from {{ build.branch }} failed. {{build.link}}
          {{ /success }}

volumes:
    - name: dockersock
      host:
          path: /var/run/docker.sock
