[package]
name = "rust_wasm"
version = "0.1.0"
authors = ["StrowBeary <remicaillot5@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.43"
js-sys = "0.3.20"
web-sys = "0.3.20"
